// The single-file headers (single/, GENERATED by tools/amalgamate). What this file pins: each is
// truly standalone (this TU's include path holds ONLY single/ — see CMakeLists), the two may
// coexist in one TU (the shared core dedupes via TACIT_SINGLE_CORE_SEEN), and re-inclusion is a
// no-op. CI additionally regenerates and diffs single/ so these can never be stale, and compiles
// the reverse include order. λ.hpp rides along pass-through.
#include "_.hpp"
#include "$.hpp"
#include "_.hpp" // re-include: no-op
#include "$.hpp" // ditto
#include "λ.hpp"

#include <cassert>
#include <functional>
#include <set>
#include <string>
#include <vector>

using tacit::_;
using tacit::$;

int main() {
  assert((_ + 1)(41) == 42);
  assert((1u <= _.size() < 4u)(std::string("ab")));
  assert($(-42).abs() == 42);
  assert(*($<std::set, _, std::greater<>>(3, 1, 2)).begin() == 3);
  assert(λ(a, b) { return a + b; }(40, 2) == 42);
  assert(tacit::lift(-1).abs() == tacit::$(-1).abs());
  return 0;
}
