// The single-file headers (single/tacit/, GENERATED by tools/amalgamate). What this file pins:
// each is truly standalone (this TU's include path holds ONLY single/ — see CMakeLists), the
// spelling is the SAME `<tacit/…>` the repo asks for, the two may coexist in one TU (the shared
// core dedupes via TACIT_SINGLE_CORE_SEEN), and re-inclusion is a no-op. CI additionally
// regenerates and diffs single/ so these can never be stale, and compiles the reverse include
// order. λ.hpp rides along pass-through.
#include <tacit/_.hpp>
#include <tacit/$.hpp>
#include <tacit/_.hpp> // re-include: no-op
#include <tacit/$.hpp> // ditto
#include <tacit/λ.hpp>

// Because the spelling no longer distinguishes them, prove we resolved to the amalgamated files and
// not to include/tacit/ (the guard exists only there); otherwise a stray -I would silently pass.
#ifndef TACIT_SINGLE_CORE_SEEN
#error "single_check resolved <tacit/_.hpp> to the repo headers, not to single/tacit/"
#endif

#include <cassert>
#include <functional>
#include <set>
#include <string>
#include <vector>

using tacit::_;
using tacit::$;

int main() {
  assert((_ + 1)(41) == 42);
  assert((1u <= _.size() < 4u)(std::string("ab")));
  assert($(-42).abs() == 42);
  assert(*($<std::set, _, std::greater<>>(3, 1, 2)).begin() == 3);
  assert(λ(a, b) { return a + b; }(40, 2) == 42);
  assert(tacit::lift(-1).abs() == tacit::$(-1).abs());
  return 0;
}
